routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Home pubblica 

Route::get('/', function () {
    return view('welcome');
});


//Utente registrato

Auth::routes();

Route::get('/home', 'PostController@index')->name('home');

Route::resource('posts', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    protected $fillable = ['title','description','user_id'];


	public function user()
	{
   		return $this->belongsTo('App\User','user_id');
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function makeRev()
    {
        $this->isAdmin = true;
        $this->save();
    }

    public function deleteRev()
    {
        $this->isAdmin = false;
        $this->save();
    }

    public function isRev(){
        return $this->isAdmin;
    }


    public function post()
   {
        return $this->hasMany('App\Post','user_id');
   }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Http\Requests\PostRequest;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        return view('home');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = new Post; //gli passo l'oggetto per usare l'old in create
        return view('posts.create', compact('post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        // The blog post is valid, store in database
   
       $post = Post::create($request->input());

       // $post= new Post;
       // $post->title=$request->input("title");
       // $post->description=$request->input("description");
       // $post->user_id=Auth::getUser()->id;
       // $post->save();

        //redirect to another page
        return redirect(route('posts.edit', [ $post->id ] ))->with('success', 'Post salvato correttamente! Qui puoi effettuare ulteriori modifiche');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $id)
    {
        $post = Post::find($id);
        $post->update($request->input());
       
        return redirect(route('posts.show', [ $post->id ] ))->with('modifiche', 'Modifiche effettuate correttamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::destroy($id);
        return redirect(route('home'))->with('modifiche', 'Post cancellato correttamente!');;   
    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
    @if (Session('modifiche'))
                <div class="alert alert-success" role="alert">
                    <strong>Successo:</strong> {{ session('modifiche') }}
                </div>
            @endif
            
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">

            

                <div class="panel-heading"><h2>BENVENUTO {{Auth::user()->name}}</h2></div>

                <div class="panel-body">

                    <h2>Questa è la tua home</h2>

                    <br>

                    <a href="{{route('posts.create')}}">Inserisci un aggiornamento su te stesso</a>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
             @endif
            <h1>Inserisci un nuovo annuncio</h1>

            <hr>
            <form action="{{route('posts.store') }}" method="POST" >
                {{ csrf_field() }}

                <input name="user_id" type="hidden" value="{{Auth::getUser()->id}}">

                <div class="form-group">
                    <label for="title" class="control-label col-xs-12">Titolo:</label>
                    <div class="col-xs-12">
                        <input type="text" name="title" class="form-control" id="title" placeholder="Titolo" value="{{ old('title', $post->title)}}">
                    </div>
                </div>

                <div class="form-group"> 
                    <label for="description" class="control-label col-xs-12">Descrizione:</label>
                    <div class="col-xs-12">
                        <textarea class="form-control" id="description" name="description">
                            {{ old('description', $post->description) }}
                        </textarea>
                    </div> 
                </div> 

                <button class="btn btn-success btn-lg btn-block" style="margin-top: 50px;">Memorizza</button>
                
            </form>
           

        </div>
    </div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
             @endif


			@if (Session('success'))
			    <div class="alert alert-success" role="alert">
			        <strong>Successo:</strong> {{ session('success') }}
			    </div>
			@endif


            <h1>Modifica l'annuncio</h1>

            <hr>

 

            <form action="{{route('posts.update', [$post->id]) }}" method="POST" >
            	{{ csrf_field() }}
            	<input type="hidden" name="_method" value="PUT">

            	<div class="form-group">
            		<label for="title" class="control-label col-xs-12">Titolo:</label>
            		<div class="col-xs-12">
            			<input type="text" name="title" class="form-control" id="title" placeholder="Titolo" value="{{ old('title', $post->title)}}">
            		</div>
            	</div>

            	<div class="form-group"> 
            		<label for="description" class="control-label col-xs-12">Descrizione:</label>
            		<div class="col-xs-12">
            			<textarea class="form-control" id="description" name="description">
            				  {{ old('description', $post->description) }}
            			</textarea>
            		</div> 
            	</div> 

            	<button class="btn btn-success btn-lg btn-block">Memorizza</button>

            </form>
            <form action="{{ route('posts.destroy', [$post->id]) }}" method="POST">
            		{{ csrf_field() }}
            		<input type="hidden" name="_method" value="DELETE">
            		<button class="btn btn-danger btn-lg btn-block">Cancella</button>
            	</form>
        </div>
    </div>
</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
	    
	    @if (Session('modifiche'))
		    <div class="alert alert-success" role="alert">
		        <strong>Successo:</strong> {{ session('modifiche') }}
		    </div>
		@endif
		<div class="col-xs-12">
        	<h1 style="text-align: center;">Anteprima Post</h1>
        </div>	

    </div>

    <div class="row" style="margin-top: 50px;">
        <div class="col-xs-2">
	       		<h1><strong>Titolo:</strong></h1>
	    </div>
	    <div class="col-xs-10"><h1>{{ $post->title }}</h1></div>
	</div>

	<div class="row">
	    <div class="col-xs-2">
	        <h2><strong>Descrizione:</strong></h2>
	    </div>
   		<div class="col-xs-10">
	        <p style="font-size: 30px;">{{ $post->description }}</p>
	    </div>
	</div>
<div class="container well">
	<div class="row text-center">
		    <div class="col-xs-6">
		        <dl class="horizontal">
		        	<dt>Creato il:</dt>
		        	<dd>{{ date('M j, Y H:i', strtotime($post->created_at)) }}</dd>
		        </dl>
		    </div>	 
		    <div class="col-xs-6">
		        <dl class="horizontal">
		        	<dt>Ultima modifica:</dt>
		        	<dd>{{ date('M j, Y H:i', strtotime($post->updated_at)) }}</dd>
		        </dl>	
		    </div>	  
		        <hr>
		        <div class="row">
		        	<div class="col-sm-6">
		        		<a href="#" class="btn btn-primary btn-block">Modifica</a>
		        	</div>
		        	<div class="col-sm-6">
		        		<a href="#" class="btn btn-danger btn-block">Cancella</a>
		        	</div>
		        </div>
		 
    </div>
</div>

    <div class="row">
	    <div class="col">
	        <a href="{{route('home')}}" class="btn btn-lg btn-primary btn-block">Ritorna alla home</a>
        </div>
     </div>

  
</div>
@endsection